### ISSUE TITLE
Feedbacks

### ISSUE THREAD

**Issue by M5oul** [ucoin-io/ucoin-ui#1]
I needed to install angular stuff:
```fish
ucoin-ui/node_modules/bower/bin/bower install
```
and also, to run the server, I had to create this repository:
```fish
mkdir ucoin-ui/public
```
Then, I don't know how to access the web page and on which port?
I have tried to modify this [file](https://github.com/ucoin-io/ucoin-ui/blob/master/app/js/lib/conf/conf.json). It correspond to the node?

**Comment by c-geek** [comment]
You should really just have to run `npm install`, which should have installed  angular stuff, create `public` repository and install files in it.

But I fixed several packaging issues since your message, could you retry now?

**Comment by c-geek** [comment]
You could also directly checkout ucoin on *master* branch, and run:

```
npm install
bin/ucoind webstart
```

It should work out-of-the-box.

**Comment by M5oul** [comment]
I have `git pull` and `npm install` ucoin and ucoin-cli repositories.
I still have an empty `public` repository. Should I restart from the beginning with `ucoin-cli`?

I could get a `cannot GET /` with curl on port 9220 after running `ucoind webstart`, but no more.

How are connected both services? I think, I saw port 8999 somewhere. I use a different port for my node.

**Comment by c-geek** [comment]
You must have node@4+, also.

**Comment by M5oul** [comment]
I have node v5.7.1.

**Comment by c-geek** [comment]
Where is `ucoin-cli` coming from? It should not be there.

**Comment by c-geek** [comment]
Oh sorry you are testing with ucoin on master branch, forget about it. It still have some issues.

But you should be able to just pull ucoin-ui and install it anyway.

**Comment by M5oul** [comment]
Sorry, I mean `ucoin-ui`.

**Comment by c-geek** [comment]
You should retry from scratch, there were issues with Node v5.

**Comment by M5oul** [comment]
I started from scratch, clone and build a second time `ucoin-ui`. Angular seems installed. `public` repo doesn't exist. I still have `Cannont GET /`.

It's not urgent :wink:
